-- Set the correct Schema
SET search_path TO bytebites;

-- Drop junction tables first
DROP TABLE IF EXISTS user_address CASCADE;
DROP TABLE IF EXISTS dish_allergen CASCADE;

-- Drop main tables
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;
DROP TABLE IF EXISTS dish CASCADE;
DROP TABLE IF EXISTS city CASCADE;
DROP TABLE IF EXISTS restaurant CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS allergens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS address CASCADE;
